<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArticlesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('articles')->insert([
            [   'name' => 'Kotovi - Avla 1',
                'site_id' => 18,
                'area' => 400,
                'details' => "ADC Disponible/ Non loin de l'école primaire publique de Kotovi" ,
                'image' => 'assets/uploads/articles_images/parcelle1.jpg',
                'normal_price' => 350.000,
                'promo_price' => 275.000,
                'disponible' => true
            ],[   'name' => 'Kotovi - Avla 2',
                'site_id' => 18,
                'area' => 500,
                'details' => "ADC Disponible/ Non loin de l'école primaire publique de Kotovi" ,
                'image' => 'assets/uploads/articles_images/parcelle2.jpg',
                'normal_price' => 425.000,
                'promo_price' => 350.000,
                'disponible' => true
            ],
            [   'name' => 'Kotovi - wogo 1',
                'site_id' => 18,
                'area' => 400,
                'details' => " Non loin du CEG AVAKPA" ,
                'image' => 'assets/uploads/articles_images/parcelle3.jpg',
                'normal_price' => 425.000,
                'promo_price' => 350.000,
                'disponible' => true
            ],
            [   'name' => 'Kotovi - wogo 2',
                'site_id' => 18,
                'area' => 500,
                'details' => " Non loin du CEG AVAKPA" ,
                'image' => 'assets/uploads/articles_images/parcelle4.jpg',
                'normal_price' => 500.000,
                'promo_price' => 425.000,
                'disponible' => true
            ],
            [   'name' => 'Avakpa - Houédo 1',
                'site_id' => 18,
                'area' => 400,
                'details' => "A 500m de l'école primaire publique de Houédo" ,
                'image' => 'assets/uploads/articles_images/parcelle5.jpg',
                'normal_price' => 475.000,
                'promo_price' => 400.000,
                'disponible' => true
            ],
            [   'name' => 'Avakpa - Houédo 2',
                'site_id' => 18,
                'area' => 500,
                'details' => "A 500m de l'école primaire publique de Houédo" ,
                'image' => 'assets/uploads/articles_images/parcelle6.jpg',
                'normal_price' => 575.000,
                'promo_price' => 500.000,
                'disponible' => true
            ],
            [   'name' => 'Vossa 1',
                'site_id' => 1,
                'area' => 400,
                'details' => "A 400m de l'epp Vossa et de l'église Catholique de Vossa" ,
                'image' => 'assets/uploads/articles_images/parcelle7.jpg',
                'normal_price' => 525.000,
                'promo_price' => 450.000,
                'disponible' => true
            ],
            [   'name' => 'Agbata',
                'site_id' => 3,
                'area' => 200,
                'details' => "Sur titre foncier/ à 600m de l'EPP Agbata avec électricité en extension" ,
                'image' => 'assets/uploads/articles_images/parcelle8.jpg',
                'normal_price' => 575.000,
                'promo_price' => 500.000,
                'disponible' => true
            ],
            [   'name' => 'Anavié',
                'site_id' => 7,
                'area' => 200,
                'details' => "Sur titre foncier. A 200m de l'école primaire Gbétaga.et à 300m de centre écotouristque Jacqueville Électricité disponible" ,
                'image' => 'assets/uploads/articles_images/parcelle1.jpg',
                'normal_price' => 675.000,
                'promo_price' => 600.000,
                'disponible' => true
            ],
            [   'name' => 'Vossa 2',
                'site_id' => 1,
                'area' => 500,
                'details' => "A 400m de l'epp Vossa et de l'église Catholique de Vossa" ,
                'image' => 'assets/uploads/articles_images/parcelle2.jpg',
                'normal_price' => 625.000,
                'promo_price' => 550.000,
                'disponible' => true
            ],
            [   'name' => 'Sogbé 6',
                'site_id' => 7,
                'area' => 200,
                'details' => "Sur titre foncier. A 500m de l'école primaire Datinnonko. Électricité disponible" ,
                'image' => 'assets/uploads/articles_images/parcelle3.jpg',
                'normal_price' => 725.000,
                'promo_price' => 650.000,
                'disponible' => true
            ],
            [   'name' => 'Sogbé 5',
                'site_id' => 7,
                'area' => 500,
                'details' => "A 500m de l'école primaire Datinnonko. Électricité disponible . électricité en extension" ,
                'image' => 'assets/uploads/articles_images/parcelle4.jpg',
                'normal_price' => 925.000,
                'promo_price' => 850.000,
                'disponible' => true
            ],
            [   'name' => 'Gbéta',
                'site_id' => 18,
                'area' => 500,
                'details' => "A 200m de l'école maternelle de Gbéta, Electricité disponible." ,
                'image' => 'assets/uploads/articles_images/parcelle5.jpg',
                'normal_price' => 775.000,
                'promo_price' => 700.000,
                'disponible' => true
            ],
            [   'name' => 'Houéhounta 1',
                'site_id' => 2,
                'area' => 400,
                'details' => "TFR Disponible/ à 700m du marché d'Agbata" ,
                'image' => 'assets/uploads/articles_images/parcelle6.jpg',
                'normal_price' => 725.000,
                'promo_price' => 650.000,
                'disponible' => true
            ],
            [   'name' => 'Houéhounta 2',
                'site_id' => 2,
                'area' => 500,
                'details' => "TFR Disponible/ à 700m du marché d'Agbata/ Zone Habitable" ,
                'image' => 'assets/uploads/articles_images/parcelle7.jpg',
                'normal_price' => 875.000,
                'promo_price' => 800.000,
                'disponible' => true
            ],
            [   'name' => 'Agbata',
                'site_id' => 4,
                'area' => 325,
                'details' => "Sur titre foncier/ à 600m de l'EPP Agbata avec électricité en extension/ zone habitée" ,
                'image' => 'assets/uploads/articles_images/parcelle8.jpg',
                'normal_price' => 875.000,
                'promo_price' => 800.000,
                'disponible' => true
            ],
            [   'name' => 'Houéhounta 1',
                'site_id' => 5,
                'area' => 400,
                'details' => "Sur titre foncier/ à 600m de l'EPP Agbata avec électricité en extension/ zone habitée" ,
                'image' => 'assets/uploads/articles_images/parcelle1.jpg',
                'normal_price' => 1050000,
                'promo_price' => 975.000,
                'disponible' => true
            ],
            [   'name' => 'Agbata',
                'site_id' => 6,
                'area' => 500,
                'details' => "Sur titre foncier/ à 600m de l'Epp Agbata avec électricité en extension " ,
                'image' => 'assets/uploads/articles_images/parcelle2.jpg',
                'normal_price' => 1400000,
                'promo_price' => 1250000,
                'disponible' => true
            ],
            [   'name' => 'Anavié 2',
                'site_id' => 7,
                'area' => 400,
                'details' => "Sur titre foncier. A 200m de l'école primaire Gbétaga.et à 300m de centre écotouristque Jacqueville Électricité disponible" ,
                'image' => 'assets/uploads/articles_images/parcelle3.jpg',
                'normal_price' => 1300000,
                'promo_price' => 1150000,
                'disponible' => true
            ],
            [   'name' => 'Tozoumè',
                'site_id' => 8,
                'area' => 500,
                'details' => "ADC disponible/à 400m du goudron et a 200m de l'école primaire publique Tozounmè" ,
                'image' => 'assets/uploads/articles_images/parcelle4.jpg',
                'normal_price' => 1400000,
                'promo_price' => 1250000,
                'disponible' => true
            ],
            [   'name' => 'Sogbé 1',
                'site_id' => 7,
                'area' => 350,
                'details' => "Sur titre foncier. A 500m de l'école primaire Datinnonko. Électricité disponible. Zone habitée" ,
                'image' => 'assets/uploads/articles_images/parcelle5.jpg',
                'normal_price' =>1250000,
                'promo_price' => 1100000,
                'disponible' => true
            ],
            [   'name' => 'Sogbé 2',
                'site_id' => 7,
                'area' => 400,
                'details' => "Sur titre foncier. A 500m de l'école primaire Datinnonko. Électricité disponible. Zone habitée" ,
                'image' => 'assets/uploads/articles_images/parcelle6.jpg',
                'normal_price' => 1400.000,
                'promo_price' => 1250000,
                'disponible' => true
            ],
            [   'name' => 'Sogbé 3',
                'site_id' => 2,
                'area' => 500,
                'details' => "Sur titre foncier.A 500m de l'école primaire Datinnonko. Électricité disponible . Zone habitée" ,
                'image' => 'assets/uploads/articles_images/parcelle7.jpg',
                'normal_price' => 1725000,
                'promo_price' => 1575000,
                'disponible' => true
            ],
            [   'name' => 'Zèbè 1',
                'site_id' => 7,
                'area' => 425,
                'details' => "A 300m de l'école primaire Zèbè et non loin de la GDIZ/ Électricité disponible . Zone très habitée" ,
                'image' => 'assets/uploads/articles_images/parcelle8.jpg',
                'normal_price' => 1650000,
                'promo_price' => 1500000,
                'disponible' => true
            ],
            [   'name' => 'Zèbè 2',
                'site_id' => 7,
                'area' => 500,
                'details' => "A 300m de l'école primaire Zèbè et non loin de la GDIZ/ Électricité disponible . Zone très habitée" ,
                'image' => 'assets/uploads/articles_images/parcelle1.jpg',
                'normal_price' => 1900000,
                'promo_price' => 1750000,
                'disponible' => true
            ],
            [   'name' => 'Mawata',
                'site_id' => 9,
                'area' => 400,
                'details' => "A 700m de l'église catholique wawata. Zone  habitée" ,
                'image' => 'assets/uploads/articles_images/parcelle2.jpg',
                'normal_price' => 1600000,
                'promo_price' => 1450000,
                'disponible' => true
            ],
            [   'name' => 'Savi / Houéyiho',
                'site_id' => 12,
                'area' => 500,
                'details' => "A 700m du Goudron et non loin de l'école primaire publique Savi - houéyiho/ Zone habitée" ,
                'image' => 'assets/uploads/articles_images/parcelle3.jpg',
                'normal_price' => 1650000,
                'promo_price' => 1500000,
                'disponible' => true
            ],
            [   'name' => 'Adimalè',
                'site_id' => 10,
                'area' => 500,
                'details' => "A l'état des lieux. A 700m du goudron et à 400m de l'Epp Adimalè . Zone Habitable." ,
                'image' => 'assets/uploads/articles_images/parcelle4.jpg',
                'normal_price' => 1450000,
                'promo_price' => 1300000,
                'disponible' => true
            ],
            [   'name' => 'Migbèhouè',
                'site_id' => 10,
                'area' => 500,
                'details' => "ADC + État des lieux /à 300m de l'EPP Migbèhouè/ Zone fortement habitée." ,
                'image' => 'assets/uploads/articles_images/parcelle5.jpg',
                'normal_price' => 2800000,
                'promo_price' => 2500000,
                'disponible' => true
            ],

            [   'name' => 'Kpossidja',
                'site_id' => 11,
                'area' => 350,
                'details' => "Sur titre foncier/ non loin de l'Epp Djigbohounhoué/ zone habitée" ,
                'image' => 'assets/uploads/articles_images/parcelle6.jpg',
                'normal_price' => 2800000,
                'promo_price' => 2500000,
                'disponible' => true
            ],
            [   'name' => 'Kpossidja',
                'site_id' => 13,
                'area' => 400,
                'details' => "Sur titre foncier/ non loin de l'Epp Djigbohounhoué/ zone habitée" ,
                'image' => 'assets/uploads/articles_images/parcelle7.jpg',
                'normal_price' => 3100000,
                'promo_price' => 2800000,
                'disponible' => true
            ],
            [   'name' => 'Adjara Hounvè',
                'site_id' => 14,
                'area' => 400,
                'details' => "Sur Titre Foncier/à près de 1km du goudron/ Zone habitée avec électricité en extension" ,
                'image' => 'assets/uploads/articles_images/parcelle8.jpg',
                'normal_price' => 4900000,
                'promo_price' => 4600000,
                'disponible' => true
            ],
            [   'name' => 'Fanto',
                'site_id' => 15,
                'area' => 400,
                'details' => "Sur Titre foncier /à 100m de l'Epp Fanto et à 1 km du goudron. Électricité disponible . Au bord de la voie principale. Zone viabilisé" ,
                'image' => 'assets/uploads/articles_images/parcelle1.jpg',
                'normal_price' => 5600000,
                'promo_price' => 5300000,
                'disponible' => true
            ],
            [   'name' => 'Awanou',
                'site_id' => 16,
                'area' => 300,
                'details' => " Lotie et recasée sur 300m²/ à 500m de l'Epp Awanou et de la voie principale Yagbé - Kétonou/ Zone habitée avec électricité disponible" ,
                'image' => 'assets/uploads/articles_images/parcelle2.jpg',
                'normal_price' => 5600000,
                'promo_price' => 5300000,
                'disponible' => true
            ],
            [   'name' => 'Houèto',
                'site_id' => 17,
                'area' => 330,
                'details' => " Lotie et recasée/ à 400m de l'église catholique de Houèto. Électricité et eau disponible" ,
                'image' => 'assets/uploads/articles_images/parcelle3.jpg',
                'normal_price' => 15000000,
                'promo_price' => 14250000,
                'disponible' => true
            ],
            [   'name' => 'Akassato',
                'site_id' => 17,
                'area' => 347,
                'details' => " Lotie , Recasée et déjà clôturé/ à 300m du goudron et de la brasserie LIBS . Zone très habitée avec électricité disponible." ,
                'image' => 'assets/uploads/articles_images/parcelle4.jpg',
                'normal_price' => 15000000,
                'promo_price' => 14250000,
                'disponible' => true
            ],


        ]);
    }
}
